Repository hackcambridge/hack-cambridge-website, pull requests merged in 2018-10, with the labels that each got.

#512 Upgrade Node to 8.12
  .travis.yml
  package.json
Labels: Epic: Dev process, Type: Maintenance

#511 Improve getting started instructions further!
  README.md
Labels: Epic: Dev process, Type: Enhancement

#507 Add YAML validation
  gulpfile.js
  package.json
  yarn.lock
Labels: Epic: Dev process, Type: Enhancement

#506 Rewrite grid system and migrate static pages
  assets/images/logo.svg
  assets/images/sponsors-logos/accenture.svg
  assets/images/sponsors-logos/amazon.svg
  assets/images/sponsors-logos/arista-networks.svg
  assets/images/sponsors-logos/ark.svg
  assets/images/sponsors-logos/arm.svg
  assets/images/sponsors-logos/avast.svg
  assets/images/sponsors-logos/cambridge-consultants.svg
  assets/images/sponsors-logos/cambridge-medical-robotics.svg
  assets/images/sponsors-logos/cisco.svg
  assets/images/sponsors-logos/cubica.svg
  assets/images/sponsors-logos/datascope.svg
  assets/images/sponsors-logos/displaylink.svg
  assets/images/sponsors-logos/droit-financial-technologies.svg
  assets/images/sponsors-logos/facebook.svg
  assets/images/sponsors-logos/featurespace.svg
  assets/images/sponsors-logos/google.svg
  assets/images/sponsors-logos/highrise.svg
  assets/images/sponsors-logos/improbable.svg
  assets/images/sponsors-logos/jp-morgan.svg
  assets/images/sponsors-logos/man-ahl.svg
  assets/images/sponsors-logos/microsoft.svg
  assets/images/sponsors-logos/sophos.svg
  assets/images/sponsors-logos/tpp.svg
  assets/images/university-of-cambridge-logo.svg
  assets/styles/all-stylesheets.css
  assets/styles/animation.css
  assets/styles/colors.css
  assets/styles/elements.css
  assets/styles/fonts.css
  assets/styles/grid.css
  assets/styles/icons.css
  assets/styles/mlh-trust-badge.css
  assets/styles/schedule.css
  assets/styles/sidebar.css
  assets/styles/ternary-cube.css
  assets/styles/text-columns.css
  assets/styles/units.css
  gulpfile.js
  package.json
  src/resources/faqs.yml
  src/resources/sponsors.yml
  src/styles/all-stylesheets.styl
  src/styles/grid.styl
  src/styles/splash.styl
  src/styles/sponsorship.styl
  src/styles/ternary.styl
  src/views/default.html
  src/views/faqs.html
  src/views/footer.html
  src/views/header.html
  src/views/index.html
  src/views/macros/svg-elements.html
  src/views/privacy-policy.html
  src/views/sponsorship.html
  src/views/terms-and-conditions.html
  yarn.lock
Labels: Epic: Dev process, Type: Enhancement

#518 Move config to JS since it is required by client-side code
  src/js/shared/dates.ts
  src/js/shared/theme.ts
  src/resources/event.yml
Labels: Type: Bug
